var stores = [
  {
    "name": "medical shop 1",
    "firm_id": "12345",
    "establishment_year": "12/12/2020",
    "street": "Kaveri Nager",
    "town": "Nellore",
    "district": "Nellore",
    "state": "Andhra pradesh",
    "isNew": false,
  },
  {
    "name": "medical shop 2",
    "firm_id": "12343",
    "establishment_year": "12/12/2020",
    "street": "Kaveri Nager",
    "town": "Nellore",
    "district": "Nellore",
    "state": "Andhra pradesh",
    "isNew": false,
  },
  {
    "name": "medical shop 3",
    "firm_id": "12342",
    "establishment_year": "12/12/2020",
    "street": "Kaveri Nager",
    "town": "Nellore",
    "district": "Nellore",
    "state": "Andhra pradesh",
    "isNew": false,
  },
  {
    "name": "",
    "firm_id": "",
    "establishment_year": "",
    "street": "",
    "town": "",
    "district": "",
    "state": "",
    "isNew": true,
  },
];
